FROM nginx:latest

RUN apt-get -y update && apt-get -y install gnupg php7.4-fpm php7.4

ADD nginx.conf /etc/nginx/nginx.conf
COPY entrypoint.sh /etc/entrypoint.sh

COPY ./web/index.php /usr/share/nginx/html
COPY ./web/eternals.png /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["chmod", "+x", "/etc/entrypoint.sh"]
