FROM debian:latest

RUN apt-get -y update && apt-get -y install gnupg php5-fpm nginx nano systemctl

ADD nginx.conf /etc/nginx/sites-available/default

COPY ./web/index.php /usr/share/nginx/www
COPY ./web/eternals.png /usr/share/nginx/www

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
