FROM nginx:latest

WORKDIR /usr/share/nginx/html
COPY ./web/index.php /usr/share/nginx/html/
COPY ./web/eternals.png /usr/share/nginx/html/

ADD nginx.conf /etc/nginx/sites-available/default.conf
COPY ./web/index.php /usr/share/nginx/html
COPY ./web/eternals.png /usr/share/nginx/html
